package io.github.workflowtool.application

import io.github.workflowtool.domain.LocalizationProvider
import io.github.workflowtool.domain.StringKey

object DefaultLocalizationProvider : LocalizationProvider {
    private val zhCn = mapOf(
        StringKey.AppTitle to "图标自动裁剪工具 v1.1.0",
        StringKey.PreviewTitle to "预览（自定义区域）",
        StringKey.LogTitle to "处理日志",
        StringKey.SelectImageTitle to "1. 选择图片",
        StringKey.SplitSettingsTitle to "2. 拆分设置",
        StringKey.OutputSettingsTitle to "3. 输出设置",
        StringKey.RegionsTitle to "区域列表",
        StringKey.ProcessTitle to "4. 处理",
        StringKey.OpenImage to "打开图片",
        StringKey.AutoMode to "自动识别",
        StringKey.GridMode to "网格拆分",
        StringKey.BaseGeneration to "基础生成",
        StringKey.ManualAdjustments to "手工修正",
        StringKey.CurrentBaseSource to "当前基础来源",
        StringKey.ManualEditsActive to "手工修正状态",
        StringKey.Regenerate to "重新生成",
        StringKey.ResetManualEdits to "重置手工修正",
        StringKey.SmartGridSettings to "智能网格参数",
        StringKey.GridColumns to "列数",
        StringKey.GridRows to "行数",
        StringKey.GridCellWidth to "单元宽",
        StringKey.GridCellHeight to "单元高",
        StringKey.SearchPadding to "搜索外扩",
        StringKey.SnapToContent to "吸附内容边界",
        StringKey.IgnoreEmptyCells to "忽略空白格",
        StringKey.TrimCellToContent to "按内容收缩单元格",
        StringKey.DrawRectangle to "绘制矩形",
        StringKey.MagicTool to "魔棒",
        StringKey.MergeNearby to "合并相邻区域",
        StringKey.RemoveSmall to "移除小区域",
        StringKey.MinSize to "最小尺寸",
        StringKey.GapThreshold to "间距阈值",
        StringKey.OutputFormat to "输出格式",
        StringKey.OutputDirectory to "输出目录",
        StringKey.NamingMode to "图标命名方式",
        StringKey.KeepOriginalSize to "保持原始大小",
        StringKey.TrimTransparent to "去除透明边距",
        StringKey.PadToSquare to "补齐为正方形",
        StringKey.SelectTool to "选择",
        StringKey.MoveTool to "移动",
        StringKey.Undo to "撤销",
        StringKey.Redo to "重做",
        StringKey.ClearRegions to "清空区域",
        StringKey.FitWindow to "适应窗口",
        StringKey.FitSelection to "适应选区",
        StringKey.GridToggle to "网格",
        StringKey.DetectionMode to "检测模式",
        StringKey.DetectionTime to "检测耗时",
        StringKey.CandidatePixels to "候选像素",
        StringKey.BackgroundEstimate to "背景估计",
        StringKey.DetectionBackend to "检测后端",
        StringKey.SelectAll to "全选",
        StringKey.InvertSelection to "反选",
        StringKey.Clear to "清空",
        StringKey.StartCrop to "开始裁剪",
        StringKey.AdvancedSettings to "高级设置",
        StringKey.OpenOutputDirectory to "打开输出目录",
        StringKey.FixedSize to "固定尺寸",
        StringKey.OverwriteExisting to "覆盖已存在文件",
        StringKey.Save to "保存",
        StringKey.Cancel to "取消"
    )

    override fun text(key: StringKey): String = zhCn.getValue(key)
}